Feature/change password
Cetus-Academy/cetusfood-back-end pull request #17
Opened 2022-08-19 19:11 UTC by Jushide

2022-08-19 19:48 UTC, husi-cetuspro commented on src/api/account/public/public.account.controller.ts
> +    	@Body('password_confirm') password_confirm: string,
Możesz poprawić formatowanie kodu? Trzeba poprawić wszędzie wcięcia itp.

Tutaj jest film Hello Romana o tym jak pisać lepszy JS i jest opisane jak możesz skonfigurować Prettier oraz ESlint: https://youtu.be/HjA_pMm86Jo, sprawdź sobie bo to Ci ułatwi pracę

2022-08-19 19:50 UTC, Jushide commented on src/api/account/public/public.account.controller.ts
> +    	@Body('password_confirm') password_confirm: string,
Wyłączyłem ostatnio prettiera bo przez niego pojawiało się wiele problemów przy mergowaniu, ale mogę to zrobić

2022-08-19 19:51 UTC, husi-cetuspro commented on src/api/account/public/public.account.controller.ts
> +		return await this.accountService.changePassword( password_old, password, password_confirm, req["user"].accId );
Zamiast `password_old` może lepiej będzie dać `password_current`? Jako aktualne hasło

A `password` dać jako `new_password`, ale to pierdoła w sumie. Może też zostać tak jak jest

2022-08-19 19:53 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +				`,
Dałbym ten kod HTML email'a do osobnej funkcji która będzie przyjmować link i inne potrzebne rzeczy i będzie zwracać gotowy HTML. Będzie przejrzyściej :)

2022-08-19 19:54 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +			const url = `http://localhost:3000/reset/${resetToken}`;
Zamiast `http://localhost:3000` trzeba pobrać adres strony z env

Zrób w env `PRODUCTION_URL` i będzie git

2022-08-19 19:55 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +				subject: 'Zmiana hasła',
Podałbym tutaj temat jako `Zmiana hasła - Cetus Food`

2022-08-19 19:57 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +				Kod jest aktywny przez następne 15 minut.
Dodałbym tutaj info w stylu `Skorzystałeś z opcji "Zapomniałem hasła" w aplikacji Cetus Food. Kliknij poniższy link, aby wprowadzić nowe hasło. Jeśli to nie ty wnioskowałeś o zmianę hasła skontaktuj się z nami na adres kontakt@cetusfood.com`

2022-08-19 19:58 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +		}
Tutaj jak warunek ma jedną linię to nie potrzebujesz klamerek. Możesz zrobić tak:

`````
		if (password !== password_confirm)
			throw new BadRequestException('Hasła do siebie nie pasują');
`````

2022-08-19 19:59 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +		}
Jak znajdziesz inne takie miejsca to możesz poprawić też

2022-08-21 08:33 UTC, Packman700 requested changes
Jest trochę rzeczy do poprawy 🙉

2022-08-21 08:33 UTC, Packman700 commented on prisma/models/order.model.prisma
> +    status       String
Status powinnien być trzymany przy pomocy ENUM od prismy

2022-08-21 08:33 UTC, Packman700 commented on prisma/models/resetPassword.model.prisma
> +}
Brakuje mi tu czasu wygaśnięcia takiego tokena 
Bo on na pewno nie powinninen mieć nielimitowanego czasu życia

2022-08-21 08:33 UTC, Packman700 commented on prisma/models/restaurant.model.prisma
> +    createdBy Int?
To powinno mieć relację z tabela `user`

2022-08-21 08:33 UTC, Packman700 commented on prisma/models/restaurant.model.prisma
> +    status    String    @default("enabled")
Ten status też powinninen być enumem

2022-08-21 08:33 UTC, Packman700 commented on prismix.config.json
>                  "./prisma/models/userLogins.model.prisma"
Zastąp to wszysko przy w ten sposób `"./prisma/models/*.model.prisma"` 
Zostaw tylko `"./prisma/base.prisma",` Jako pierwszy input

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +    	@Body('password_confirm') password_confirm: string
To jest bardzo nie elegancjie rozwiązanie stosowanie `@Body("nazwa_parametru")` 
Powinniście przejść na `@Body() data: ResertPasswordDto`. Jak kożystacie z dto to możecie np odrazu przeprwadzać tam walidacje :P

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +		return await this.accountService.resetPassword( resetToken, password, password_confirm );
Jak dodasz te dto to tutaj przekaż cały obiekt a w śrdku serwiu dopiero wypakuj sobie dane

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +    	@Body('password_confirm') password_confirm: string,
Użyj DTO

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +			const url = `http://localhost:3000/reset/${resetToken}`;
+1

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +				html:
Nie jestem pewny z jakiej usługi do maili kożytasz ale na pewno ma on wbudowany support do edytorów typu `Handlebars.js` Jest to stokroć ładniejsze rozwiązanie

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +			await this.addDeleteTokenTimeout(email);
Oj tak nie rób jak. W ten sposób tracisz dane.
Lepiej dodać kolumne w bazie danych z datą wygaśnięcia tokenu.
I podczas próby użycia powinineś sprawdzać czy token jest dalej aktywny

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +	}
Możesz usunąć te else jest zbędne

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +		}
Myślę że to moża wszystko do osobnej metody wyeksportować + tak jak wcześniej pisałem niepotrzebnie użyasz else w końcu podczas pierwszego wywołania `return` albo `throw` funkcja nie wykonuje już kodu poniżej

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +
Powiem to znowu zrezygnuj z tego :')

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
>  	}
Ta metoda może być prywatna

2022-08-21 08:33 UTC, Packman700 commented on src/api/restaurants/admin/admin.restaurants.service.ts
> +import { ResteurantStatus } from 'src/enums/resteurant.status.enum';
Ten import wyrzuci ci error. Niestety nest js nie ma wbudoanych absolotnych ścieżek :<

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +	public async forgotPassword(email: string) {
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +	){
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +	){
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +	async addDeleteTokenTimeout(email){
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +	async getHashedPassword(password: string, hashedPassword: string) {
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
>  	public async verifyAccount(@Param('guid') guid: string) {
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +	public async forgotPassword(@Body('email') email: string) {
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +	public async resetPassword(
Brak zwracanego typu

2022-08-21 08:33 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +	public async changePassword(
Brak zwracanego typu

2022-08-21 10:37 UTC, Jushide commented on prisma/models/order.model.prisma
> +    status       String
Jak generuje prismix mając enum w modelu order, który ktoś zrobił, w wygenerowanym pliku schema.prisma mam błąd przez który nie mogę zrobić migracji.
![image](https://user-images.githubusercontent.com/93134991/185787043-3eaaca7a-1ff3-4a8b-a3d6-1050eda60365.png)

2022-08-22 13:43 UTC, Jushide commented on prisma/models/order.model.prisma
> +    status       String
Do bazy danych używamy SQLite, nie wspiera chyba typu enum w pliku przez to.

2022-08-24 06:48 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +                message: response,
Nie dawałbym tekstu 'Jeśli podany email istnieje, to wyślemy ci wiadomość ze zmianą hasła' do osobnej zmiennej. 

Ewentualnie jak już to nazwałbym tą zmienną `successResponseMessage` aby było bardziej wiadomo o co chodzi :)

2022-08-24 06:50 UTC, Jushide commented on src/api/account/public/public.account.service.ts
> +                message: response,
Zrobiłem tak z myślą by nie zmieniać potem zawartości tekstu w kilku miejscach jeśli i tak mają być takie same

2022-08-24 19:24 UTC, Packman700 reviewed
GG duży progress 🔥

2022-08-24 19:24 UTC, Packman700 commented on src/api/account/account.dto.ts
>  export class RegisterAccountDto {
Ogólnie dobrą praktyką jest trzymanie każdego dto w osobnym pliku

2022-08-24 19:24 UTC, Packman700 commented on src/api/account/account.dto.ts
Idk czemu nie masz tutaj walidacji 
Jeśli jest to response jaki zwraca endpoint to przyjmij sobie inną kowencję dla takich klass np Entity

2022-08-24 19:24 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +    public async forgotPassword(@Body() dto: ForgotPasswordDto): Promise<any> {
any jak zwracny typ to jest mały progress ale najlepszą praktyką jaka znam jest stoswanie entiy jako rsposne jak to zrobisz to pokażę ci jeszcze jak możesz wykożystać te entity dla swaggera

```ts
import { Exclude, Expose } from "class-transformer"
import { ApiProperty } from "@nestjs/swagger"

@Exclude()
export class GeoLocalizationEntity {
    @ApiProperty()
    @Expose()
    lat: number

    @ApiProperty()
    @Expose()
    lng: number

    constructor(partial: Partial<GeoLocalizationEntity>) {
        Object.assign(this, partial)
    }
}
```
^
 |
Przykład entity

2022-08-24 19:24 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +
Dwie rzeczy po pierwsze nie widzę powodu dla którego rozpbiłeś ustawienie daty wygaśnięcia na dwie linijki a po drugie dobrą praktyką jest unikanie używania tzw `magicznych liczb`
Jak chcesz to lepiej napisać to spróbuj coś takiego
```
const ONE_MINUTE_IN_MICROSECONDS = 1000
cosnt ONE_HOUR_IS_MINUTES = 15
```

2022-08-24 19:24 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +        const url = `${process.env.PRODUCTION_URL}/reset/${resetToken}`;
Napisz dokładnie co ten url oznacza

2022-08-24 19:24 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +        if (dto.password_new !== dto.password_confirm)
`const isPaswordValid = dto.password_new !== dto.password_confirm`

2022-08-24 19:24 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +        const isMatch = await this.getHashedPassword(dto.password_new, userEmailIsValid.password);
Lepszą nazwą byłoby isPasswordMatch
Albo tutaj nawet bardziej `isPasswordChanged = !(await this.getHashedPassword(dto.password_new, userEmailIsValid.password);)`

2022-08-24 19:24 UTC, Packman700 commented on src/api/restaurants/admin/admin.restaurants.service.ts
> +import { ResteurantStatus } from 'src/enums/resteurant.status.enum';
Jak to działa to daj mi znać na pv 
U mnie w projekcie takie coś zwraca błędy (masz jakiś config pod to?)

2022-08-24 19:24 UTC, Packman700 commented on src/mail/mail.service.ts
> +    @Cron('0 8 * * 1-5')
Crony są badzio nie czytelne dla ludzi
Przenieś to do jakiejść stałej z opisem 
```ts
const EVERY_MIDWEEK_DAY_ON_8_AM = '0 8 * * 1-5'
```

2022-08-24 19:24 UTC, Packman700 commented on src/mail/mail.service.ts
> -  }
Nie podoba mi się że w jednej klasie masz crona i metody 
Zastanów się jak podzielić te funkcjonoalności na dwa pliki

2022-08-24 19:29 UTC, Hubciodx2 commented on src/api/account/public/public.account.service.ts
> +                password: hashedPassword,
A jeszcze pytanie, czy robimy tutaj walidację pod kątem złożoności hasła? :) Warto byłoby dodać jakieś reguły tutaj jak i podczas tworzenia konta. Możesz pod to stworzyć ewentualnie osobnego taska

2022-08-24 19:32 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +        });
A jeszcze pytanie, czy robimy tutaj walidację pod kątem złożoności hasła? :) Warto byłoby dodać jakieś reguły co do długości, znaków specjalnych itp. Warto byłoby dodać tutaj jak i podczas tworzenia konta. Możesz pod to stworzyć ewentualnie osobnego taska

2022-08-24 19:36 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +        const hashedPassword = this.sharedAccountService.genHashPassword(dto.password_new);
Można ewentualnie jeszcze wydzielić metodę do zmiany hasła do osobnej funkcji. Kilka rzeczy tutaj się sprawdza, a pewnie to samo robisz również podczas tworzenia konta. Taką samą metodę będziemy mieć jeszcze podczas zmiany hasła z poziomu panelu użytkownika itp.

2022-08-24 19:50 UTC, Jushide commented on src/api/account/public/public.account.service.ts
> +        });
Nie ma tu walidacji sprawdzającej takich rzeczy, spróbuje ją zrobić, a jak nie dam rady to dodam taska do zrobienia potem.

2022-08-26 08:54 UTC, Jushide commented on src/api/account/public/public.account.service.ts
> +
@Packman700 a jak można ustawić datę wygaśnięcia w jednej linijce? I gdzie mam przechowywać zmienne, o których mówisz?

2022-08-26 12:41 UTC, Jushide commented on src/api/account/public/public.account.service.ts
> +        const hashedPassword = this.sharedAccountService.genHashPassword(dto.password_new);
@husi-cetuspro próbowałem to zrobić na kilka sposobów, ale jedna funkcja działa przez szukanie konta z użyciem emaila a druga funkcja pobiera ID konta zawartego w accessTokenie, funkcje działają na różnych zasadach, więc nie wiem jak to można zrobić.

2022-08-28 08:39 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +        const hashedPassword = this.sharedAccountService.genHashPassword(dto.password_new);
Chodziło mi o to abyś zrobił własną osobną prywatną metodę. Możesz zapytać się Dominika gdzie najlepiej taką metodę będzie umieścić bo za bardzo nie znam NestJS

2022-08-28 08:40 UTC, husi-cetuspro commented on src/api/account/public/public.account.service.ts
> +        });
Spoko 😄 Możesz śmiało zrobić osobnego taska

2022-08-29 07:03 UTC, Jushide commented on src/api/account/public/public.account.service.ts
> +        const hashedPassword = this.sharedAccountService.genHashPassword(dto.password_new);
@husi-cetuspro udało mi się to jednak zrobić, zrobiłem skróconego if sprawdzającego typ odbieranych danych, potestuje jeszcze i zrobię pusha.

2022-09-07 06:20 UTC, Packman700 requested changes
GG

2022-09-07 06:20 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +    }
O super jak już kożystasz z entity to możesz dodać taki fragment kodu
```
    @ApiResponse({
        status: 200,
        type: ResponseMessageEntity,
    })
```
I zerknij na swaggera jak wygląda teraz body

2022-09-07 06:20 UTC, Packman700 commented on src/api/account/public/public.account.controller.ts
> +        return await this.accountService.changePassword(req['user'].accId, dto);
Jak wyciągasz tylko accId to zrób sobie dekorator do wyciągnięcia id ussera

2022-09-07 06:20 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +        let accountModel: AccountModel;
Nie potrzebnie ustalasz to na początku metody skoro i tak tylko w jednym miejsu (linijka 150) zapisujesz dane do zmiennej

2022-09-07 06:20 UTC, Packman700 commented on src/api/account/public/public.account.service.ts
> +}
Do po prawy. Parametry sugerują że idnetyfikator może być tylko stringiem a jednak to sprawdzasz 
Rozwiązanie `identificator: string|number` 
Zwykłe spawdzanie typów w js też jest średnie suguruje użycie pacztki `isWhat` i metody `isString()` będzie czytalniej 

A poza tym nie powinieneś wyszukiwać po emailu xD

2022-09-07 06:20 UTC, Packman700 commented on src/cron/mails/cron.mails.service.ts
> +        let accounts = await this.prismaService.account.findMany();
Dlaczego nie użyłeś `const`?

2022-09-07 06:20 UTC, Packman700 commented on src/mail/mail.service.ts
> +    }
Dlaczego wszytkie metody są async jak nigdzie nie wykożystujesz tej asunchroniczności :?
O i nie masz tu nigidze typów (nawet `void` to duża informacja)

2022-09-09 15:57 UTC, Jushide commented
![](https://github.trello.services/images/mini-trello-icon.png) [Resetowanie hasła](https://trello.com/c/0VQqHitG/55-resetowanie-has%C5%82a)

2022-09-17 15:33 UTC, merged