Filtrowany endpoint
Cetus-Academy/cetusfood-back-end pull request #18
Opened 2022-10-06 17:30 UTC by Jushide

2022-10-06 17:57 UTC, Packman700 requested changes
GG

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.controller.ts
> +import { filterAdminDto } from "../dto/filterAdmin.dto";
FilterAdminDto

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +        if (id) {
Osobny endpoint

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +        }
filter factory

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +    public async getVerifiedUsers(): Promise<AccountModel[]> {
Nazwa funkji nie mówi prawdy

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +            });
??? + brak await xD

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +            Logger.log(`Zaakceptowano użytkownika`);
Raczej zbędne to

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +        if (result.count < 1) {
result.count === 0

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +        const result = await this.prismaService.account.deleteMany({
Przed usunięciem odpal metodę getAccountById() i usuń tą walidachę poniżej

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +        return await this.sharedAccountService.registerAccount(dto, Role.ADMIN, false);
Usunąc tą flagę na końcu i użyć tu try cach jak nie powinno być błędu

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    isVerified: boolean;
IsBoolean

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    id: number;
@IsInt

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    isAccepted: boolean;
@IsBoolean

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    email: string;
@IsString()

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    id: number;
id?: number;

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    email: string;
email?: string;

2022-10-06 17:57 UTC, Packman700 commented on src/api/account/entities/AccountModel.entity.ts
> +}
Rozbij na dwa entity

2022-10-08 20:54 UTC, Jushide commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Admin] Zmiana zdublowanych endpointów GET na jeden filtrowany](https://trello.com/c/ocKPiH39/111-admin-zmiana-zdublowanych-endpoint%C3%B3w-get-na-jeden-filtrowany)

2022-10-10 20:05 UTC, Jushide commented on src/api/account/admin/admin.account.service.ts
> +        return await this.sharedAccountService.registerAccount(dto, Role.ADMIN, false);
jak usuwam false, wywala serwer albo komunikaty, że konto istnieje i nie można go utworzyć, więc narazie tak zostawie i wywale niedlugo niepotrzebne loggery itd

2022-10-11 07:13 UTC, Packman700 reviewed
Już tylko drobne rzeczy zostały

2022-10-11 07:13 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +    }
Koxunio tylko przeniósłbym to do osobnej klasy

2022-10-11 07:13 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +    static getAccountsByFilters(filters): Prisma.AccountWhereInput {
Tutaj nie masz typu filtrów może to być np DTO z wszystkimi typami albo interfejs

2022-10-11 07:13 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +    public async getAccountsByFilters(filters): Promise<AccountModel[]> {
Tutaj nie masz typu dla filtrów powinno to być DTO z kontrolera

2022-10-11 07:13 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +    }
U mnie mam  osobny moduł w którym po prostu seeduje tego typu dane
Trzeba uważać na to by każda klasa robiła tylko jedną rzecz
Teraz jest ona odpowiedzila za seedowanie, kotakt z bazą danych, parsowanie dantch, tworzenie filtrów
A poteniclanie można to wszystko rozbić
Ale sam zdecyduj czy jest sens na tym etapie to wydzilać

2022-10-11 07:13 UTC, Packman700 commented on src/api/account/admin/admin.account.service.ts
> +    public async getAccountById(id: number) {
Wrr nie zwracasz tu typu

2022-10-11 07:13 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    // @IsBoolean()
Tą walidację to już warto dodać ;P

2022-10-11 07:13 UTC, Packman700 commented on src/api/account/dto/filterAdmin.dto.ts
> +    // @IsBoolean()
Tą walidację to już warto dodać ;P v2

2022-10-12 14:25 UTC, merged